### PR TITLE
Added Package.swift for Swift Package Manager support

### PR DESCRIPTION
**Pull request by mluisbrown**
Tested using `swift build` from the latest development drop of Swift.

### CODE REVIEW

**Comment by dmcrodrigues** [comment]
Build :white_check_mark: 

:sparkles:

**Comment by dmcrodrigues** [comment]
Closes #46.

**Comment by RuiAAPeres** [comment]
Not sure if [this](https://medium.com/swift-and-ios-writing/swift-package-manager-tutorial-59ade1fc708d#.jflrebyav) is still up to date but:

> You will need to make sure your .Swift files are in a Sources folder.

All the packages [here](https://swiftpkgs.ng.bluemix.net/) follow that.

**Comment by dmcrodrigues** [comment]
I'm not sure if that is still required.
> It is acceptable to have no Sources directory, in which case the root directory is treated as a single module (place your sources there) or sub directories of the root are considered modules.
*Reference*: [Source Layouts](https://github.com/apple/swift-package-manager/blob/master/Documentation/SourceLayouts.md)

Maybe we should run some tests to be sure.

**Comment by RuiAAPeres** [comment]
I think we should go with Source to be sure:

> (...)or sub directories of the root are considered modules.

In our case it would work.

**Comment by mluisbrown** [comment]
I tested it with the layout we have now and it works. `swift build` in the root creates  `.build/debug/Vinyl.swiftmodule`. .swiftmodule files can be imported into other projects. I had to add an `exclude` section in `Package.swift` so that VinylTests and Carthage folders are ignored.

**Comment by RuiAAPeres** [comment]
@mluisbrown y good job.

**Comment by mluisbrown** [comment]
Also, see [this thread](https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20160222/001305.html) on swift-users mailing list. Confirms that .swiftmodule output is all you need to import module into a client package.

**Pull request merged**
