### PR TITLE
Add support for uploadTaskWithRequest

### PR DESCRIPTION
**Pull request by Sephiroth87**

### CODE REVIEW

**Comment by dmcrodrigues** [comment]
@Sephiroth87 Thanks for this :sparkles:  

Can you include a test to contemplate this addition?

**Comment by Sephiroth87** [comment]
No problem

**Comment by RuiAAPeres** [comment]
Looks good! ✨

**Comment by dmcrodrigues** [comment]
Great work @Sephiroth87! 🎉

**Comment by dmcrodrigues** [comment]
🏍

**Pull request merged**
