### PR TITLE
Add Podspec

### PR DESCRIPTION
**Pull request by Sephiroth87**
Not submitted to Trunk yet...

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Bro, we are waiting for v1.0 to do that. :stuck_out_tongue:

**Comment by RuiAAPeres** [comment]
I am  locking this until we push 1.0. Sorry bro. :+1:

**Comment by dmcrodrigues** [comment]
@Sephiroth87 we can merge this without submitting to CocoaPods at least for now, we're planning to do that with 1.0.

I tested this using your fork and it can be easily used by pointing to the repository and branch/commit.

``` ruby

**Comment by dmcrodrigues** [comment]
@Sephiroth87 But before merging, can I ask you to squash/rebase the last two commits? 😊 We would like to avoid them in history. Let me know if that's ok.

**Comment by Sephiroth87** [comment]
Done 👍

**Comment by dmcrodrigues** [comment]
Thanks :sparkles:

**Comment by dmcrodrigues** [comment]
🏎

**Pull request merged**
