### PR TITLE
Play tracks uniquely

### PR DESCRIPTION
**Pull request by dmcrodrigues**

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Is there a test for this feature? I am seeing this:

```
-            requestMatcherTypes: [.URL])
 +            turntableConfiguration: TurntableConfiguration(requestMatcherTypes: [.URL]))
```

But could we test when the configuration allows to not play tracks uniquely?

**Comment by dmcrodrigues** [comment]
Good catch! Test included :white_check_mark:

**Comment by dmcrodrigues** [comment]
Great :sparkles:

**Comment by dmcrodrigues** [comment]
:truck:

**Pull request merged**
